// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quiz_api.Entities;

#nullable disable

namespace quiz_api.Entities.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240116203608_add_max_score")]
    partial class add_max_score
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("quiz_api.Entities.Models.Answer", b =>
                {
                    b.Property<int>("QuizId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ChoiceId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("QuizId", "QuestionId", "ChoiceId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("quiz_api.Entities.Models.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("point")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChoiceText = "วาฬสีน้ำเงิน",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 1,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 2,
                            ChoiceText = "ปลาวาฬสเปิร์ม",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 1,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 4
                        },
                        new
                        {
                            Id = 3,
                            ChoiceText = "ปลาฉลามวาฬ",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 1,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 3
                        },
                        new
                        {
                            Id = 4,
                            ChoiceText = "ปลาฉลามขาว",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 1,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 5,
                            ChoiceText = "ปลาดาว",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 2,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 6,
                            ChoiceText = "ปลาทอง",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 2,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 4
                        },
                        new
                        {
                            Id = 7,
                            ChoiceText = "กุ้งก้ามกราม",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 2,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 3
                        },
                        new
                        {
                            Id = 8,
                            ChoiceText = "เต่า",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 2,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 9,
                            ChoiceText = "ปลาฉลาม",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 3,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 10,
                            ChoiceText = "ปลาโลมา",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 3,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 4
                        },
                        new
                        {
                            Id = 11,
                            ChoiceText = "ปลาหมึกยักษ์",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 3,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 3
                        },
                        new
                        {
                            Id = 12,
                            ChoiceText = "ปลากระเบน",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 3,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 13,
                            ChoiceText = "ปลาฉลาม",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 4,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 4
                        },
                        new
                        {
                            Id = 14,
                            ChoiceText = "ปลาโลมา",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 4,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 15,
                            ChoiceText = "ปลาหมึกยักษ์",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 4,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 16,
                            ChoiceText = "วาฬสเปิร์ม",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 4,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 3
                        },
                        new
                        {
                            Id = 17,
                            ChoiceText = "ปลาฉลามวาฬ",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 5,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 18,
                            ChoiceText = "ปลาโลมา",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 5,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 4
                        },
                        new
                        {
                            Id = 19,
                            ChoiceText = "ปลาหมึกยักษ์",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 5,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 20,
                            ChoiceText = "แมงมุมน้ำ",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 5,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 0
                        },
                        new
                        {
                            Id = 21,
                            ChoiceText = "นก",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 6,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 22,
                            ChoiceText = "ค้างคาว",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 6,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 4
                        },
                        new
                        {
                            Id = 23,
                            ChoiceText = "กบ",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 6,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 24,
                            ChoiceText = "สุนัข",
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 6,
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 0
                        },
                        new
                        {
                            Id = 25,
                            ChoiceText = "ช้างแอฟริกัน",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 7,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 26,
                            ChoiceText = "วัวกระทิง",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 7,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 4
                        },
                        new
                        {
                            Id = 27,
                            ChoiceText = "สิงโต",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 7,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 3
                        },
                        new
                        {
                            Id = 28,
                            ChoiceText = "ลิงอุรังอุตัง",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 7,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 29,
                            ChoiceText = "วัว",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 8,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 30,
                            ChoiceText = "ช้าง",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 8,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 4
                        },
                        new
                        {
                            Id = 31,
                            ChoiceText = "ม้า",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 8,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 3
                        },
                        new
                        {
                            Id = 32,
                            ChoiceText = "แมว",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 8,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 33,
                            ChoiceText = "ช้าง",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 9,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 34,
                            ChoiceText = "วัว",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 9,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 4
                        },
                        new
                        {
                            Id = 35,
                            ChoiceText = "ม้า",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 9,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 3
                        },
                        new
                        {
                            Id = 36,
                            ChoiceText = "แมว",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 9,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 37,
                            ChoiceText = "อูฐ",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 10,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 38,
                            ChoiceText = "ยีราฟ",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 10,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 4
                        },
                        new
                        {
                            Id = 39,
                            ChoiceText = "ม้าลาย",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 10,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 3
                        },
                        new
                        {
                            Id = 40,
                            ChoiceText = "สิงโต",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 10,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 41,
                            ChoiceText = "นกกระจอกเทศ",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 11,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 42,
                            ChoiceText = "นกแก้ว",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 11,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 0
                        },
                        new
                        {
                            Id = 43,
                            ChoiceText = "นกเป็ด",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 11,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 44,
                            ChoiceText = "นกยูง",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 11,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 1
                        },
                        new
                        {
                            Id = 45,
                            ChoiceText = "นก",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 12,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 46,
                            ChoiceText = "ค้างคาว",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 12,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 0
                        },
                        new
                        {
                            Id = 47,
                            ChoiceText = "เต่า",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 12,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 48,
                            ChoiceText = "ปลา",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 12,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 1
                        },
                        new
                        {
                            Id = 49,
                            ChoiceText = "นกเป็ดน้ำ",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 13,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 50,
                            ChoiceText = "นกกระจอกเทศ",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 13,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 0
                        },
                        new
                        {
                            Id = 51,
                            ChoiceText = "นกแก้ว",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 13,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 52,
                            ChoiceText = "นกยูง",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 13,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 1
                        },
                        new
                        {
                            Id = 53,
                            ChoiceText = "นกกระจอกเทศ",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 14,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 54,
                            ChoiceText = "นกแก้ว",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 14,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 3
                        },
                        new
                        {
                            Id = 55,
                            ChoiceText = "นกเป็ด",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 14,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        },
                        new
                        {
                            Id = 56,
                            ChoiceText = "นกยูง",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 14,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 1
                        },
                        new
                        {
                            Id = 57,
                            ChoiceText = "ไก่",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 15,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 5
                        },
                        new
                        {
                            Id = 58,
                            ChoiceText = "นกกระจอกเทศ",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 15,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 4
                        },
                        new
                        {
                            Id = 59,
                            ChoiceText = "นกแก้ว",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 15,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 3
                        },
                        new
                        {
                            Id = 60,
                            ChoiceText = "นกยูง",
                            CreateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            QuestionId = 15,
                            UpdateDate = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            point = 2
                        });
                });

            modelBuilder.Entity("quiz_api.Entities.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            Name = "สัตว์น้ำ",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            Name = "สัตว์บก",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inactive = false,
                            Name = "สัตว์มีปีก",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("quiz_api.Entities.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 1,
                            Inactive = false,
                            QuestionText = "สัตว์น้ำชนิดใดที่มีขนาดใหญ่ที่สุดในโลก",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 1,
                            Inactive = false,
                            QuestionText = "สัตว์น้ำชนิดใดที่อาศัยอยู่ในน้ำจืด",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 1,
                            Inactive = false,
                            QuestionText = "สัตว์น้ำชนิดใดที่กินเนื้อเป็นอาหาร",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 3
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 1,
                            Inactive = false,
                            QuestionText = "สัตว์น้ำชนิดใดที่อาศัยอยู่ในทะเลลึก",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 4
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 1,
                            Inactive = false,
                            QuestionText = "สัตว์น้ำชนิดใดที่กินปลาวาฬเป็นอาหาร",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 5
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 2,
                            Inactive = false,
                            QuestionText = "สัตว์บกชนิดใดที่มีความสามารถในการบินได้",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 1
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 2,
                            Inactive = false,
                            QuestionText = "สัตว์บกชนิดใดที่ใหญ่ที่สุดในโลก",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 2
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 2,
                            Inactive = false,
                            QuestionText = "สัตว์บกชนิดใดที่กินพืชเป็นอาหาร",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 3
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 2,
                            Inactive = false,
                            QuestionText = "สัตว์บกชนิดใดที่ออกลูกเป็นตัว",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 4
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 2,
                            Inactive = false,
                            QuestionText = "สัตว์บกชนิดใดที่อาศัยอยู่ในทะเลทราย",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 5
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 3,
                            Inactive = false,
                            QuestionText = "สัตว์ปีกที่บินไม่ได้คืออะไร?",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 1
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 3,
                            Inactive = false,
                            QuestionText = "สัตว์ปีกที่ออกลูกเป็นไข่คืออะไร?",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 2
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 3,
                            Inactive = false,
                            QuestionText = "สัตว์ปีกที่อาศัยอยู่ในน้ำคืออะไร?",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 3
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 3,
                            Inactive = false,
                            QuestionText = "สัตว์ปีกที่กินพืชเป็นอาหารคืออะไร?",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 4
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 3,
                            Inactive = false,
                            QuestionText = "สัตว์ปีกที่มีความสำคัญต่อมนุษย์คืออะไร?",
                            UpdateDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            order = 5
                        });
                });

            modelBuilder.Entity("quiz_api.Entities.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("quiz_api.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("quiz_api.Entities.Models.Answer", b =>
                {
                    b.HasOne("quiz_api.Entities.Models.Quiz", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("quiz_api.Entities.Models.Choice", b =>
                {
                    b.HasOne("quiz_api.Entities.Models.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("quiz_api.Entities.Models.Question", b =>
                {
                    b.HasOne("quiz_api.Entities.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("quiz_api.Entities.Models.Quiz", b =>
                {
                    b.HasOne("quiz_api.Entities.Models.Group", null)
                        .WithMany("Quizzes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("quiz_api.Entities.Models.User", b =>
                {
                    b.HasOne("quiz_api.Entities.Models.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("quiz_api.Entities.Models.Group", b =>
                {
                    b.Navigation("Quizzes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("quiz_api.Entities.Models.Question", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("quiz_api.Entities.Models.Quiz", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
